// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqOXU16AFobz3G-J-Wb52lpjYPKgp628',
    appId: '1:345964728818:web:f60291ba92d20525645b6b',
    messagingSenderId: '345964728818',
    projectId: 'etlearn-9ed52',
    authDomain: 'etlearn-9ed52.firebaseapp.com',
    storageBucket: 'etlearn-9ed52.firebasestorage.app',
    measurementId: 'G-ME0L5MD37B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXskQv0S7BC6ubDYxjPt22jLzXQ_QoGWA',
    appId: '1:345964728818:android:0d739aac99f27701645b6b',
    messagingSenderId: '345964728818',
    projectId: 'etlearn-9ed52',
    storageBucket: 'etlearn-9ed52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBIaFC0c4u2bgxKGSpNXx1kFL0XqzE9co',
    appId: '1:345964728818:ios:038cb13c734ba2e5645b6b',
    messagingSenderId: '345964728818',
    projectId: 'etlearn-9ed52',
    storageBucket: 'etlearn-9ed52.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBIaFC0c4u2bgxKGSpNXx1kFL0XqzE9co',
    appId: '1:345964728818:ios:038cb13c734ba2e5645b6b',
    messagingSenderId: '345964728818',
    projectId: 'etlearn-9ed52',
    storageBucket: 'etlearn-9ed52.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqOXU16AFobz3G-J-Wb52lpjYPKgp628',
    appId: '1:345964728818:web:5dac459fe6fe5a56645b6b',
    messagingSenderId: '345964728818',
    projectId: 'etlearn-9ed52',
    authDomain: 'etlearn-9ed52.firebaseapp.com',
    storageBucket: 'etlearn-9ed52.firebasestorage.app',
    measurementId: 'G-Z16Z172XZH',
  );
}
